damaba:
  web-url: http://damaba.test
  auth:
    jwt-secret: jwtSecretForOnlyTestEnvironment12345678901234567890

spring:
  datasource:
    # Test용 embedded DB 설정
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  sql:
    init:
      mode: embedded
      schema-locations: classpath:schema.sql
      data-locations:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

aws:
  s3:
    bucket-name: aws-s3-bucket-name
    access-key: aws-s3-access-key
    secret-key: aws-s3-secret-key

logging:
  level:
    com.damaba: debug
    org:
      hibernate:
        type: trace
        SQL: debug
