spring:
  sql.init.mode: always

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: false

springdoc:
  show-actuator: true

logging:
  level:
    com.damaba: debug
    org:
      hibernate:
        type: trace
        SQL: debug
