name: CI for prod

on:
  pull_request:
    branches: [ "main" ]

env:
  ENV_FILE_NAME: env.properties
  DAMABA_ENV_DIR: ./damaba/src/main/resources

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set environments
        run: echo "${{secrets.DEV_ENV}}" > $DAMABA_ENV_DIR/$ENV_FILE_NAME

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
